version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=tourdb
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"

